apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-conversao
spec:
    replicas: 5
    selector:
        matchLabels:
            app: api-conversao
    template:
        metadata:
            labels:
                app: api-conversao
        spec:
            containers:
                - name: api-conversao
                  image: stthrudell/api-conversao:v1 
                  ports:
                      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: svc-api-conversao
spec:
    selector:
        app: api-conversao
    ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
    type: NodePort
